name: geoflutterfireblaze
description: The packages allows to easily configure your project.
maintainer: Sofiane Akbly
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.0
  rxdart: ^0.27.7
